export const CODE_BLOCK_LANGUAGES: Record<string, string> = {
  text: "Plain text",
  bash: "Bash",
  sh: "Shell",
  powershell: "PowerShell",
  c: "C",
  cpp: "C++",
  cs: "C#",
  css: "CSS",
  scss: "SCSS",
  less: "LESS",
  go: "Go",
  html: "HTML",
  xml: "XML",
  java: "Java",
  javascript: "JavaScript",
  js: "JavaScript",
  jsx: "JSX",
  json: "JSON",
  kotlin: "Kotlin",
  markdown: "Markdown",
  md: "Markdown",
  php: "PHP",
  python: "Python",
  ruby: "Ruby",
  rust: "Rust",
  scala: "Scala",
  sql: "SQL",
  swift: "Swift",
  toml: "TOML",
  typescript: "TypeScript",
  ts: "TypeScript",
  tsx: "TSX",
  yaml: "YAML",
  yml: "YAML",
  dockerfile: "Dockerfile",
};
